
name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Conan
        uses: turtlebrowser/get-conan@v1.0
      
      - name: Create default profile
        run: conan profile new default --detect
      
      - name: Update profile
        run: conan profile update settings.compiler.libcxx=libstdc++11 default
      
      - name: Install dependencies
        run: conan install . --install-folder=${{github.workspace}}/build
      - name: Build using conan
        run: (cd build && conan build ../conanfile.py && cd ..) 
      - name: Package conan 
        run: conan package . --build-folder=build --package-folder=_package
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
        # Artifact name
         name: libCommonAPI.so.3.2.0
         # A file, directory or wildcard pattern that describes what to upload
         path: _package

