
name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Conan
        uses: turtlebrowser/get-conan@v1.0
      
      - name: Create default profile
        run: conan profile new default --detect
      
      - name: Update profile
        run: conan profile update settings.compiler.libcxx=libstdc++11 default
      
      - name: Install dependencies
        run: conan install . --install-folder=${{github.workspace}}/build
      - name: Build using conan
        run: (cd build && conan build ../conanfile.py && cd ..) 
      - name: copy built artifacts to a safe folder 
        run: mkdir _bin | cp build/lib* _bin | echo "_bin contains" | ls _bin
      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download
          path: _bin
        
     
