
name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Conan
        uses: turtlebrowser/get-conan@v1.0
      
      - name: Create default profile
        run: conan profile new default --detect
      
      - name: Update profile
        run: conan profile update settings.compiler.libcxx=libstdc++11 default
      
      - name: Install dependencies
        run: conan install . -s --install-folder=${{github.workspace}}/build
