
name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Conan
        uses: turtlebrowser/get-conan@v1.0
      
      - name: Create default profile
        run: conan profile new default --detect
      
      - name: Update profile
        run: conan profile update settings.compiler.libcxx=libstdc++11 default
      
      - name: Install dependencies
        run: conan install . --install-folder=${{github.workspace}}/build
      - name: Build using conan
        run: (cd build && conan build ../conanfile.py && cd ..) 
      - name: Package conan 
        run: conan package . --build-folder=build --package-folder=_package
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
